[package]

name = "bitfield"
version = "0.0.1"
authors = ["Loïc Damien <loic.damien@dzamlo.ch>"]
description = "A procedural macro to generate bitfield-like stuct"

[lib]
name = "bitfield"
plugin = true

